FROM python:3.7-slim

WORKDIR /usr/src/project

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py collectstatic --no-input

CMD gunicorn -b 0.0.0.0:$PORT expensesproject.wsgi:application
